#!/bin/bash
language=${1:-""}
sed -i.bak "s/#let varLanguage = \".*\"/#let varLanguage = \"$language\"/" metadata.typ

echo "Language set to '$language' in metadata.typ"

typst compile ./cv.typ ./output/CV.pdf --font-path ./src/fonts/